### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by rdtandel** [sbamniya/razorpayx-nodejs-sdk#1]
I'm trying to use this in serverless api. Its running in local invoke but on aws lambda not working. getting following error.

`{
  "errorType": "Runtime.UserCodeSyntaxError",
  "errorMessage": "SyntaxError: Unexpected token =",
  "trace": [
    "Runtime.UserCodeSyntaxError: SyntaxError: Unexpected token =",
    "    at _loadUserApp (/var/runtime/UserFunction.js:98:13)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
    "    at Object.<anonymous> (/var/runtime/index.js:45:30)",
    "    at Module._compile (internal/modules/cjs/loader.js:778:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)",
    "    at Module.load (internal/modules/cjs/loader.js:653:32)",
    "    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:585:3)",
    "    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)",
    "    at startup (internal/bootstrap/node.js:283:19)"
  ]
}`

**Comment by sbamniya** [comment]
Which version of NodeJS your lambda function is built on?

**Comment by sbamniya** [comment]
Check out the latest version. I've added support for older version of nodejs.

**Comment by rdtandel** [comment]
> Which version of NodeJS your lambda function is built on?

nodejs10.x

**Comment by rdtandel** [comment]
> Check out the latest version. I've added support for older version of nodejs.

I've updated But, still getting error.

**Comment by sbamniya** [comment]
try running on Node 12. also seems like the package is not updated. Have you tried removing package-lock.json and try reinstalling the package?
