### ISSUE TITLE
Error in PayoutLink Cancel Method

### ISSUE THREAD

**Issue by EquinoxSoftwareApplications** [sbamniya/razorpayx-nodejs-sdk#6]
Hi @sbamniya, @mansurishahrukh007 

Please have a look at PayoutLink Cancel Method.
Line `/${payoutLinkId}/${cancel}` should be replaced with `/${payoutLinkId}/cancel` in PayoutLink.js

having ${cancel} makes compiler to consider cancel as variable as a result PayoutLink Cancel action results into below error

{
  code: undefined,
  isError: true,
  timestamp: 1642791500746,
  error: 'Unknown error',
  messages: [ 'The requested URL was not found on the server.' ],
  data: {
      code: 'BAD_REQUEST_ERROR',
      description: 'The requested URL was not found on the server.',
      source: 'NA',
      step: 'NA',
      reason: 'NA',
      metadata: {}
    }
  }
}

Please fix this ASAP.

**Comment by sbamniya** [comment]
This has been fixed in #7

**Comment by sbamniya** [comment]
it is fixed in version 1.0.3
